const API='http://localhost:5000/api';let token=localStorage.getItem('token');
const $=id=>document.getElementById(id);
async function loadJobs(){const q=$('search').value,type=$('type').value;const r=await fetch(`${API}/internships?q=${encodeURIComponent(q)}&type=${encodeURIComponent(type)}`);const jobs=await r.json();$('jobs').innerHTML=jobs.map(j=>`<article class="job"><div class="muted">${j.company} • ${j.location}</div><h3>${j.role}</h3><div>${(j.skills||[]).map(s=>`<span class="chip">${s}</span>`).join('')}</div><p class="muted">${j.description||''}</p><b>${j.stipend||'Stipend not specified'}</b><button class="apply" onclick="apply('${j._id}')">Apply Now</button></article>`).join('')||'<p>No internships found.</p>'}
async function apply(id){if(!token)return showAuth('login');const r=await fetch(`${API}/applications/${id}`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});const d=await r.json();alert(d.message||'Application submitted');loadApps()}
async function loadApps(){if(!token)return;$('apps').innerHTML='Loading...';const r=await fetch(`${API}/applications/my`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)return;$('apps').innerHTML=(await r.json()).map(a=>`<div class="application"><div><b>${a.internship.role}</b><div class="muted">${a.internship.company}</div></div><span class="status">${a.status}</span></div>`).join('')||'<p class="muted">No applications yet.</p>'}
function showAuth(mode){$('modal').classList.remove('hidden');$('authTitle').textContent=mode==='login'?'Login':'Create account';$('nameWrap').style.display=mode==='login'?'none':'block';$('authForm').dataset.mode=mode}
function hideAuth(){$('modal').classList.add('hidden')}
$('authForm').onsubmit=async e=>{e.preventDefault();const mode=e.target.dataset.mode;const body={email:$('email').value,password:$('password').value};if(mode==='register')body.name=$('name').value;const r=await fetch(`${API}/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){$('authMsg').textContent=d.message;return}token=d.token;localStorage.setItem('token',token);hideAuth();loadApps();alert('Logged in successfully')};
loadJobs();loadApps();
